name       : haskell-system-filepath
version    : 0.4.13.4
release    : 1
source     :
    - http://hackage.haskell.org/package/system-filepath-0.4.13.4/system-filepath-0.4.13.4.tar.gz : 345d7dec968b74ab1b8c0e7bb78c2ef1e5be7be6b7bac455340fd658abfec5fb
license    : MIT
component  : programming.haskell
summary    : Provides a FilePath datatype and utility functions for operating on it. Unlike the filepath package, this package does not simply reuse String, increasing type safety.
description: |
    Provides a FilePath datatype and utility functions for operating on it. Unlike the filepath package, this package does not simply reuse String, increasing type safety.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
