name       : haskell-system-filepath
version    : 0.4.14
release    : 4
source     :
    - https://hackage.haskell.org/package/system-filepath-0.4.14/system-filepath-0.4.14.tar.gz : 1656ce3c0d585650784ceb3f794748286e19fb635f557e7b29b0897f8956d993
license    : MIT
component  : programming.haskell
summary    : Provides a FilePath datatype and utility functions for operating on it. Unlike the filepath package, this package does not simply reuse String, increasing type safety.
description: |
    Provides a FilePath datatype and utility functions for operating on it. Unlike the filepath package, this package does not simply reuse String, increasing type safety.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
